[package]
name = "seismic"
version = "0.1.0"

[dependencies]
starknet = ">=2.3.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.19.0" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"

[cairo]
sierra-replace-ids = true
